### ISSUE TITLE
cannot init db due to google_client_id

### ISSUE THREAD

**Issue by scenaristeur** [SamurAIGPT/Camel-AutoGPT#6]
flask db init
```
Traceback (most recent call last):
  File "/home/user/dev/Camel-AutoGPT/server/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/user/dev/Camel-AutoGPT/server/venv/lib/python3.10/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/home/user/dev/Camel-AutoGPT/server/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/dev/Camel-AutoGPT/server/venv/lib/python3.10/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/user/dev/Camel-AutoGPT/server/venv/lib/python3.10/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/user/dev/Camel-AutoGPT/server/venv/lib/python3.10/site-packages/flask/cli.py", line 578, in get_command
    app = info.load_app()
  File "/home/user/dev/Camel-AutoGPT/server/venv/lib/python3.10/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/home/user/dev/Camel-AutoGPT/server/venv/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/home/user/dev/Camel-AutoGPT/server/webserver.py", line 15, in <module>
    from agent_convo import rp
  File "/home/user/dev/Camel-AutoGPT/server/agent_convo.py", line 28, in <module>
    google_client_id = os.environ['google_client_id']
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'google_client_id'
```
any idea ? 
Thxs

**Comment by rolandpg** [comment]
Same issue:  running this on an Ubuntu 23.xx OS

(Camel-AutoGPT) rolandpg@Odin:~/Camel-AutoGPT/server$ flask db init
Traceback (most recent call last):
  File "/home/rolandpg/Camel-AutoGPT/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/rolandpg/Camel-AutoGPT/lib/python3.11/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/home/rolandpg/Camel-AutoGPT/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/rolandpg/Camel-AutoGPT/lib/python3.11/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rolandpg/Camel-AutoGPT/lib/python3.11/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rolandpg/Camel-AutoGPT/lib/python3.11/site-packages/flask/cli.py", line 578, in get_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/home/rolandpg/Camel-AutoGPT/lib/python3.11/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rolandpg/Camel-AutoGPT/lib/python3.11/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/home/rolandpg/Camel-AutoGPT/server/webserver.py", line 15, in <module>
    from agent_convo import rp
  File "/home/rolandpg/Camel-AutoGPT/server/agent_convo.py", line 28, in <module>
    google_client_id = os.environ['google_client_id']
                       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
